### ISSUE TITLE
How can I add cache to the public worker?

### ISSUE THREAD

**Issue by iamdarkle** [cmackenzie1/r2-public-worker#2]
Hi, thank you very much for creating this, it's a great help! Right now I've just started all this R2 stuff, there is hardly any guide beyond the docs. Do you know how I could include cache to your repository? I've been doing some research in the docs and some projects (https://community.cloudflare.com/t/how-to-cache-workers-responses-with-r2-backend/386408), but honestly I don't know exactly how to do it, I hope you can help me 🙂

**Comment by cmackenzie1** [comment]
@iamdarkle, hopefully this example can help you find what you are looking for :) https://github.com/kotx/render

**Comment by iamdarkle** [comment]
Unfortunately that repository only supports read not upload which is something I need 😕

**Comment by cmackenzie1** [comment]
@iamdarkle, apologies but that is out of the scope of this example. This is just for serving the content already in a bucket. Your best resource would be the [developer docs](https://developers.cloudflare.com/r2/runtime-apis/#bucket-method-definitions)
